---

- name: create project directory
  file:
    path: /opt/python/{{ project_name }}
    state: directory
    owner: deploy

- name: Create systemd config file for project
  template: src=project.service.j2 dest="/etc/systemd/system/{{ project_name }}.service"
  notify: Reload project service

- name: Append proxypass statements to apache config
  blockinfile:
    path: /confs/{{ web_server_name }}/{{ vhost_shortname }}.conf
    block: |
      <Location "/{{ project_name }}">
          PassengerEnabled off
      </Location>
      ProxyPass /{{ project_name }} http://localhost:8000/
      ProxyPassReverse /{{ project_name }} http://localhost:8000/
  notify: Reload Apache
